####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CFLAGS = -g -Wall -O2 -I./src
LIBS =
NAME = smake
ODIR = obj
OBJ = o

OBJS = xstr.$(OBJ) \
	file.$(OBJ) \
	smake.$(OBJ) \
	info.$(OBJ) \
	make.$(OBJ) \
	slog.$(OBJ) \
	cfg.$(OBJ) \
	xjson.$(OBJ)

OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))
INSTALL_BIN = /usr/bin
VPATH = ./src

.c.$(OBJ):
	@test -d $(ODIR) || mkdir -p $(ODIR)
	$(CC) $(CFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(CC) $(CFLAGS) -o $(ODIR)/$(NAME) $(OBJECTS) $(LIBS)

.PHONY: install
install:
	@test -d $(INSTALL_BIN) || mkdir -p $(INSTALL_BIN)
	@install -m 0755 $(ODIR)/$(NAME) $(INSTALL_BIN)/

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)